<?php
// Automatically Generated by TestLink Installer - Thu, 12 Oct 23 17:22:22 +0200
define('DB_TYPE', 'mysql');
define('DB_USER', 'admin');
define('DB_PASS', 'admin');
define('DB_HOST', 'localhost');
define('DB_NAME', 'test');
define('DB_TABLE_PREFIX', '');
